# pubspec.yaml
name: useful_lints
version: 0.0.1
description: A set of useful src for Flutter projects.
homepage: https://github.com/tsnAnh-dev/useful_lints/
repository: https://github.com/tsnAnh-dev/useful_lints/

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0
  collection: ^1.18.0